
name: Build Sigil AppImage

on:
 workflow_dispatch:

jobs:
  build:
    #if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout Sigil
      uses: actions/checkout@v4
      with:
        repository: sigil-ebook/Sigil
        ref: master
        path: website

    - name: Set up Python 3.13.2
      uses: actions/setup-python@v5
      with:
        python-version: 3.13.2

    - name: Cache Qt
      id: cache-qt
      uses: actions/cache@v4
      with:
        path: ${{runner.workspace}}/Qt
        key: ${{ runner.os }}-sigilqt-${{ hashFiles('**/reset-lin-caches.txt') }}
  
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.8.2'
        dir: ${{runner.workspace}}/Qt
        modules: 'qtwebengine qtpositioning qtpdf qtwebchannel'
        setup-python: 'false'
        cache: ${{ steps.cache-qt.outputs.cache-hit }}

    - uses: lukka/get-cmake@latest

    - name: Install dependencies
      run: |
        sudo apt install mesa-common-dev libglu1-mesa-dev
        mkdir ${{runner.workspace}}/build
        which cmake
        cmake --version
        ninja --version
        qmake -v
        python3 --version
        which python3
        gcc --version

    #- name: Upload Artifact
    #  uses: actions/upload-artifact@v4
    #  with:
    #    name: AppImage-artifact
    #    path: sigil-qt6-python3.11_x86_64.AppImage
    #    retention-days: 8

