
name: Pull upstream Subtree ref

on:
  workflow_dispatch:
    inputs:
      ref_name:
        description: 'Upstream ref to pull'
        required: true
        default: ''

jobs:

  build:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to THIS repository.
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: master
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull upstream changes into subtree
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git subtree pull --prefix sigil_src https://github.com/Sigil-Ebook/Sigil.git ${{ github.event.inputs.ref_name }} --squash

      - name: Update Subree with Sigil ref
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Pull upstream subtree ref ${{ github.event.inputs.ref_name }}
